version: "3.9"

services:
  formsDB:
    image: postgres:17.7
    container_name: formsDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
